Added Templates support to the Config Governance SDK
IBM/scc-go-sdk pull request #32
Opened 2021-06-25 16:57 UTC by NickXitco

## PR summary
Added Templates support to the Config Governance SDK.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features) (API Docs PR in progress)

## Current vs new behavior  
Only current behavior being modified is patching a small bug in the Config Governance Integration tests, where running it on an account with unlabeled rules would cause a crash in the `AfterSuite()` function.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

## Other information

2021-07-14 02:49 UTC, ashishth09 requested changes

2021-07-14 02:49 UTC, ashishth09 commented on go.sum
> +github.com/IBM/platform-services-go-sdk v0.18.18 h1:xMxM6SJH5ke04e49Mbdjmpy1po5KmvP1VE8VCzF2GAY=
We shouldn't depend on platform-services-go-sdk.
Please run go mod  tidy

2021-07-14 05:48 UTC, ashishth09 commented on go.sum
> +github.com/IBM/platform-services-go-sdk v0.18.18 h1:xMxM6SJH5ke04e49Mbdjmpy1po5KmvP1VE8VCzF2GAY=
Also run go fmt ./...

2021-07-14 16:54 UTC, gary1998 commented
- You need to rebase your branch with latest `main` branch. The ITs of `notificationsv1` have been fixed.

2021-07-14 21:30 UTC, NickXitco commented
> You need to rebase your branch with latest `main` branch. The ITs of `notificationsv1` have been fixed.

Can you elaborate on this? The branch is based on the latest `main` branch as far as I can see and rebasing had no effect.

2021-07-14 21:31 UTC, NickXitco commented
Otherwise I believe the correct changes have been made

2021-07-15 03:49 UTC, ashishth09 commented
Included in https://github.com/IBM/scc-go-sdk/pull/38 @NickXitco gave you access to create branch directly on this repo.
The integration tests required credentials available only for the pull requests from this repo.

2021-07-15 03:49 UTC, closed without merging