Added Admin Services SDK
IBM/scc-go-sdk pull request #33
Opened 2021-06-25 17:20 UTC by NickXitco

## PR summary
Added Admin Services SDK

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [X] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features) (API docs in progress)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [X] No

## Other information

2021-07-14 02:41 UTC, ashishth09 requested changes

2021-07-14 02:41 UTC, ashishth09 commented on go.mod
> +	github.com/IBM/platform-services-go-sdk v0.18.18 // indirect
We shouldn't depend on platform-services-go-sdk. I see you used it for composing the headers, please use github.com/IBM/scc-go-sdk/common instead.

2021-07-14 03:00 UTC, ashishth09 commented
@NickXitco please run 
```
go fmt ./...
```
from the root project

2021-07-14 15:55 UTC, gary1998 commented
Couple of changes are required:
- Need to replace the import statement on `https://github.com/NickXitco/scc-go-sdk/blob/admin_services_sdk/adminserviceapiv1/admin_service_api_v1.go#L33` to `common "github.com/IBM/scc-go-sdk/common"`
- Once the above change is placed, do run `go mod tidy` to update the `go.mod` and `go.sum`
- Another change is to add `echo "${ADMIN_SERVICE_ENV}" | base64 -d >> admin_services_v1.env` to `build/testScript.sh` before `make test-int` command.

2021-07-15 03:09 UTC, merged

2021-07-15 03:49 UTC, sccdeveloper commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/scc-go-sdk/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: